version: "3.9"

volumes: 
  dbdata: 

services: 
  db: 
    image: postgres:14
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web: 
    build: .
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes: 
      - .:/myapp
    ports: 
      - 3000:3000
    depends_on: 
      - db